import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:flutter_timezone/flutter_timezone.dart';
import 'package:life_os/core/scheduling/civil_date.dart';
import 'package:life_os/core/utils/first_value.dart';
import 'package:life_os/data/local/daos/activity_log_dao.dart';
import 'package:life_os/data/local/daos/event_dao.dart';
import 'package:life_os/data/local/daos/goal_dao.dart';
import 'package:life_os/data/local/daos/plan_dao.dart';
import 'package:life_os/data/local/daos/preferences_dao.dart';
import 'package:life_os/data/local/daos/project_dao.dart';
import 'package:life_os/data/local/daos/task_dao.dart';
import 'package:life_os/data/local/database.dart';
import 'package:life_os/data/repositories/event_repository.dart';
import 'package:life_os/data/repositories/goal_repository.dart';
import 'package:life_os/data/repositories/models/app_goal.dart';
import 'package:life_os/data/repositories/models/app_plan.dart';
import 'package:life_os/data/repositories/models/app_project.dart';
import 'package:life_os/data/repositories/plan_repository.dart';
import 'package:life_os/data/repositories/preferences_repository.dart';
import 'package:life_os/data/repositories/project_repository.dart';
import 'package:life_os/data/repositories/task_repository.dart';
import 'package:timezone/data/latest_all.dart' as tz_data;
import 'package:timezone/timezone.dart' as tz;

const _channelId = 'life_os_reminders';
const _channelName = 'Reminders';
const _channelDescription = 'Task, plan, habit, event, project and goal reminders';

/// How far ahead to look for candidates. Anything further out gets picked
/// up on a later reschedule (§22.3: "reschedules on ... app resume") —
/// there is no value in holding thousands of far-future alarms the OS
/// might never even keep once the per-platform cap below is applied.
const _horizonDays = 14;

const _maxAndroidNotifications = 200;
const _maxIosNotifications = 56;

/// One category per §22.3's togglable list. `taskDeadlines`,
/// `morningBriefing`, `eveningBriefing`, `freeTimeNudges` and
/// `weeklyReview` aren't generated by anything here yet — see
/// DECISIONS.md for why each is deferred. Public (not `_`-prefixed)
/// specifically so `NotificationScheduler.buildSchedule` — the
/// candidate-generation-and-filtering half, with no plugin calls in it —
/// is unit-testable without needing a fake `FlutterLocalNotificationsPlugin`.
class NotificationCandidate {
  NotificationCandidate({
    required this.preferenceKey,
    required this.title,
    required this.body,
    required this.scheduledAt,
    required this.payload,
  });

  final String preferenceKey;
  final String title;
  final String body;
  final DateTime scheduledAt;
  final String payload;

  int get id => '$payload@${scheduledAt.toIso8601String()}'.hashCode & 0x7FFFFFFF;
}

/// §22.3. Local-only — no server, no push. One scheduler owns every
/// category so nothing risks scheduling directly and bypassing the
/// master switch, per-category toggles or quiet hours. Exact alarms
/// (`SCHEDULE_EXACT_ALARM`) are never requested: every notification here
/// is inexact (`AndroidScheduleMode.inexactAllowWhileIdle`), matching the
/// spec's own "a few minutes of drift is irrelevant" allowance for
/// briefings/deadline warnings, extended to everything in this pass
/// rather than building a second, exact-alarm-seeking path for a v1 that
/// doesn't have those categories yet anyway. See DECISIONS.md.
class NotificationScheduler {
  NotificationScheduler(AppDatabase db)
    : _taskRepository = TaskRepository(TaskDao(db)),
      _planRepository = PlanRepository(PlanDao(db), ActivityLogDao(db)),
      _eventRepository = EventRepository(EventDao(db)),
      _projectRepository = ProjectRepository(ProjectDao(db)),
      _goalRepository = GoalRepository(GoalDao(db)),
      _preferencesRepository = PreferencesRepository(PreferencesDao(db));

  final TaskRepository _taskRepository;
  final PlanRepository _planRepository;
  final EventRepository _eventRepository;
  final ProjectRepository _projectRepository;
  final GoalRepository _goalRepository;
  final PreferencesRepository _preferencesRepository;

  final _plugin = FlutterLocalNotificationsPlugin();
  bool _pluginInitialized = false;
  ValueChanged<String>? _onNotificationTap;

  /// Cheap and safe to call any time, whether or not notifications are
  /// enabled yet — it just records where a tap should route to, and does
  /// nothing platform-visible. Kept separate from the actual plugin
  /// init/permission-request below so the real handler can be registered
  /// on every app resume regardless of the master switch, while the
  /// permission prompt itself only fires from [rescheduleAll] once that
  /// switch is genuinely on. See DECISIONS.md.
  @visibleForTesting
  ValueChanged<String>? get notificationTapHandler => _onNotificationTap;
  set notificationTapHandler(ValueChanged<String> handler) {
    _onNotificationTap = handler;
  }

  /// Requests the OS notification permission on first call — must only be
  /// reached once `notif.master` is confirmed on (see [rescheduleAll]), or
  /// the prompt fires before the user has ever opted in.
  Future<void> _ensureInitialized() async {
    if (_pluginInitialized) return;
    _pluginInitialized = true;

    tz_data.initializeTimeZones();
    try {
      final info = await FlutterTimezone.getLocalTimezone();
      tz.setLocalLocation(tz.getLocation(info.identifier));
    } on Object {
      // A device reporting an id the `timezone` package doesn't recognise
      // is rare but not impossible — falling back to UTC means times can
      // be wrong by the device's offset rather than the app crashing.
    }

    await _plugin.initialize(
      settings: const InitializationSettings(
        android: AndroidInitializationSettings('@mipmap/ic_launcher'),
        iOS: DarwinInitializationSettings(),
      ),
      onDidReceiveNotificationResponse: (response) {
        final payload = response.payload;
        if (payload != null) _onNotificationTap?.call(payload);
      },
    );

    final android = _plugin.resolvePlatformSpecificImplementation<AndroidFlutterLocalNotificationsPlugin>();
    await android?.requestNotificationsPermission();
    await _plugin
        .resolvePlatformSpecificImplementation<IOSFlutterLocalNotificationsPlugin>()
        ?.requestPermissions(alert: true, badge: true, sound: true);
  }

  /// Cancels everything and reschedules from scratch. Cheap enough at
  /// personal-app scale to just always do a full rebuild rather than
  /// diff against what's already scheduled — see DECISIONS.md.
  ///
  /// Checks the master switch itself, before touching the plugin at all:
  /// this is what the Settings screen calls the instant someone flips that
  /// switch on, and it's the correct moment for the OS permission prompt
  /// to appear — not app launch, and not `buildSchedule`'s own (later,
  /// candidate-filtering) master check, which would let a plugin call
  /// through first.
  Future<void> rescheduleAll(String userId) async {
    final master = await _boolPref(userId, 'notif.master');
    if (!master) {
      if (_pluginInitialized) await _plugin.cancelAll();
      return;
    }

    await _ensureInitialized();
    await _plugin.cancelAll();
    final schedule = await buildSchedule(userId);
    for (final candidate in schedule) {
      await _plugin.zonedSchedule(
        id: candidate.id,
        scheduledDate: tz.TZDateTime.from(candidate.scheduledAt, tz.local),
        title: candidate.title,
        body: candidate.body,
        payload: candidate.payload,
        androidScheduleMode: AndroidScheduleMode.inexactAllowWhileIdle,
        notificationDetails: const NotificationDetails(
          android: AndroidNotificationDetails(_channelId, _channelName, channelDescription: _channelDescription),
          iOS: DarwinNotificationDetails(),
        ),
      );
    }
  }

  /// The candidate-generation-through-capping pipeline, with no plugin
  /// calls in it at all — every rule §22.3 asks for (master switch,
  /// per-category toggles, quiet hours, future-only, sorted-by-time,
  /// platform cap) lives here, where a test can call it directly against
  /// a real in-memory database and assert on the result.
  @visibleForTesting
  Future<List<NotificationCandidate>> buildSchedule(String userId) async {
    final master = await _boolPref(userId, 'notif.master');
    if (!master) return [];

    final quietStart = await _stringPref(userId, 'notif.quietStart');
    final quietEnd = await _stringPref(userId, 'notif.quietEnd');

    final today = CivilDate.fromDateTime(DateTime.now());
    final horizon = today.addDays(_horizonDays);
    final now = DateTime.now();

    final candidates = <NotificationCandidate>[
      ...await _taskCandidates(userId),
      ...await _planCandidates(userId, today, horizon, habits: false),
      ...await _planCandidates(userId, today, horizon, habits: true),
      ...await _eventCandidates(userId, today, horizon),
      ...await _projectDeadlineCandidates(userId, today, horizon),
      ...await _goalMilestoneCandidates(userId, today, horizon),
    ];

    final enabled = <NotificationCandidate>[];
    for (final candidate in candidates) {
      if (!candidate.scheduledAt.isAfter(now)) continue;
      if (!await _boolPref(userId, candidate.preferenceKey)) continue;
      if (_inQuietHours(candidate.scheduledAt, quietStart, quietEnd)) continue;
      enabled.add(candidate);
    }
    enabled.sort((a, b) => a.scheduledAt.compareTo(b.scheduledAt));

    final cap = Platform.isIOS ? _maxIosNotifications : _maxAndroidNotifications;
    return enabled.take(cap).toList();
  }

  Future<bool> _boolPref(String userId, String key) async {
    final result = await _preferencesRepository.get(userId, key);
    return result.when(ok: (value) => value == 'true', err: (_) => false);
  }

  Future<String?> _stringPref(String userId, String key) async {
    final result = await _preferencesRepository.get(userId, key);
    return result.when(ok: (value) => value, err: (_) => null);
  }

  bool _inQuietHours(DateTime at, String? start, String? end) {
    if (start == null || end == null) return false;
    final startMinutes = _minutesOf(start);
    final endMinutes = _minutesOf(end);
    final atMinutes = at.hour * 60 + at.minute;
    if (startMinutes == null || endMinutes == null) return false;
    if (startMinutes <= endMinutes) {
      return atMinutes >= startMinutes && atMinutes < endMinutes;
    }
    // Overnight window (e.g. 22:00-07:00) wraps past midnight.
    return atMinutes >= startMinutes || atMinutes < endMinutes;
  }

  int? _minutesOf(String hhmm) {
    final parts = hhmm.split(':');
    if (parts.length != 2) return null;
    final hour = int.tryParse(parts[0]);
    final minute = int.tryParse(parts[1]);
    if (hour == null || minute == null) return null;
    return hour * 60 + minute;
  }

  DateTime _atTime(CivilDate date, String? hhmm, {int fallbackHour = 9}) {
    final minutes = hhmm == null ? null : _minutesOf(hhmm);
    if (minutes == null) return DateTime(date.year, date.month, date.day, fallbackHour);
    return DateTime(date.year, date.month, date.day, minutes ~/ 60, minutes % 60);
  }

  Future<List<NotificationCandidate>> _taskCandidates(String userId) async {
    final tasks = await firstValue(_taskRepository.watchUpcoming(userId, CivilDate.fromDateTime(DateTime.now())));
    return [
      for (final task in tasks)
        if (task.dueDate != null && !task.isCompleted)
          NotificationCandidate(
            preferenceKey: 'notif.taskReminders',
            title: 'Task due',
            body: task.title,
            scheduledAt: _atTime(CivilDate.parse(task.dueDate!), task.dueTime),
            payload: 'task:${task.id}',
          ),
    ];
  }

  Future<List<NotificationCandidate>> _planCandidates(
    String userId,
    CivilDate today,
    CivilDate horizon, {
    required bool habits,
  }) async {
    final plans = await firstValue(habits ? _planRepository.watchHabits(userId) : _planRepository.watchActive(userId));
    final planById = <String, AppPlan>{for (final plan in plans) plan.id: plan};
    if (planById.isEmpty) return [];

    final occurrences = await firstValue(_planRepository.watchOccurrencesInRange(userId, today, horizon));
    final key = habits ? 'notif.habitReminders' : 'notif.planOccurrences';
    return [
      for (final occurrence in occurrences)
        if (planById[occurrence.planId] case final plan? when occurrence.status == OccurrenceStatus.pending)
          if (occurrence.scheduledTime ?? plan.timeOfDay case final time?)
            NotificationCandidate(
              preferenceKey: key,
              title: habits ? 'Habit' : 'Plan',
              body: plan.title,
              scheduledAt: _atTime(occurrence.scheduledDate, time),
              payload: 'plan:${plan.id}',
            ),
    ];
  }

  Future<List<NotificationCandidate>> _eventCandidates(String userId, CivilDate today, CivilDate horizon) async {
    final events = await firstValue(_eventRepository.watchInRange(userId, today, horizon));
    return [
      for (final event in events)
        if (!event.allDay)
          NotificationCandidate(
            preferenceKey: 'notif.eventAlerts',
            title: 'Event',
            body: event.title,
            scheduledAt: event.startAt,
            payload: 'event:${event.id}',
          ),
    ];
  }

  Future<List<NotificationCandidate>> _projectDeadlineCandidates(String userId, CivilDate today, CivilDate horizon) async {
    final projects = await firstValue(_projectRepository.watchAll(userId));
    return [
      for (final project in projects)
        if (project.status == ProjectStatus.active)
          if (project.deadline case final deadline? when !deadline.isBefore(today) && !deadline.isAfter(horizon))
            NotificationCandidate(
              preferenceKey: 'notif.projectDeadlines',
              title: 'Project deadline',
              body: project.title,
              scheduledAt: _atTime(deadline, null),
              payload: 'project:${project.id}',
            ),
    ];
  }

  Future<List<NotificationCandidate>> _goalMilestoneCandidates(String userId, CivilDate today, CivilDate horizon) async {
    final goals = await firstValue(_goalRepository.watchAll(userId));
    final activeGoals = goals.where((g) => g.status == GoalStatus.active);
    final candidates = <NotificationCandidate>[];
    for (final goal in activeGoals) {
      final milestones = await firstValue(_goalRepository.watchMilestones(goal.id));
      for (final milestone in milestones) {
        final due = milestone.dueDate;
        if (milestone.isCompleted || due == null) continue;
        if (due.isBefore(today) || due.isAfter(horizon)) continue;
        candidates.add(
          NotificationCandidate(
            preferenceKey: 'notif.goalMilestones',
            title: 'Goal milestone',
            body: milestone.title ?? goal.title,
            scheduledAt: _atTime(due, null),
            payload: 'goal:${goal.id}',
          ),
        );
      }
    }
    return candidates;
  }
}
